name: todo_app_cifo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.2
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_app.png
  android: true
  ios: true
  web: false
  android_gravity: center

  android_12:
    image: assets/logo_app.png
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/logo_app.png


    
    